name: 'Check CI Status'
description: 'Verifies that CI checks have passed before proceeding'

runs:
  using: composite
  steps:
    - name: Verify CI Passed
      uses: actions/github-script@v7
      with:
        script: |
          const { data: checks } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload.pull_request.head.sha
          });

          const ciChecks = checks.check_runs.filter(check => check.name === 'CI Checks');

          if (ciChecks.length === 0) {
            core.setFailed('❌ CI Checks not found. Please wait for CI to run first.');
            return;
          }

          const successfulRun = ciChecks.find(check => check.conclusion === 'success');

          if (!successfulRun) {
            const latestRun = ciChecks[0];
            const status = latestRun.conclusion || latestRun.status;
            core.setFailed(`❌ CI Checks must pass before proceeding. Latest status: ${status}`);
            return;
          }

          core.info(`✅ CI Checks passed (run ${successfulRun.id})`);
