name: 'Security Scan'
description: 'Run incremental security scan on skills catalog'

inputs:
  artifact-name:
    description: 'Name for the uploaded scan results artifact'
    required: true
  retention-days:
    description: 'Number of days to retain the artifact'
    required: false
    default: '7'

outputs:
  scan-outcome:
    description: 'Outcome of the security scan step (success/failure)'
    value: ${{ steps.scan.outcome }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Restore scan cache
      uses: actions/cache@v4
      with:
        path: .security-scan-cache.json
        key: security-scan-v1-${{ hashFiles('packages/skills-catalog/skills/**/*') }}
        restore-keys: security-scan-v1-

    - name: Run security scan
      id: scan
      shell: bash
      run: npx nx run @tech-leads-club/skills-catalog:security-scan || NX_NO_CLOUD=true npx nx run @tech-leads-club/skills-catalog:security-scan
      continue-on-error: true

    - name: Upload scan results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: .security-scan-results.json
        retention-days: ${{ inputs.retention-days }}
        include-hidden-files: true
