name: "Snapshot Notification"
description: "Comments on PR with snapshot version and removes label"

inputs:
  github-token:
    description: "GitHub token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Check for Existing Snapshot Comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const {version} = require('./packages/cli/package.json');
          const alreadyCommented = comments.some(comment =>
            comment.body.includes(`agent-skills@${version}`)
          );

          if (alreadyCommented) {
            core.setFailed(`âš ï¸ Snapshot ${version} already published and commented.`);
          }

    - name: Comment Snapshot Version
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const {version} = require('./packages/cli/package.json');
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `ðŸš€ **Snapshot Published!**\n\n\`\`\`bash\nnpm install @tech-leads-club/agent-skills@${version}\n\`\`\``
          });

    - name: Add Published Label
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          await github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['snapshot: published']
          });

    - name: Remove Action Label
      if: always()
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          await github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'action: snapshot'
          }).catch(() => {});
